export const experiences = {
  en: [
    {
      company: "AXIANS CYBERSECURITY",
      role: "Full Stack Web Developer",
      period: "Jun 2021 - Present",
      location: "TUNISIA",
      type: "REMOTE",
      description:
        "Development of the 'CERT Axians IT' platform which offers alert, information, supervision, and analysis services to protect against computer attacks.",
      highlights: [
        "Malware Analysis Integration: Integrated an automated malware analysis module with Cuckoo Sandbox for enhanced security insights.",
        "Search Engine with Sphinx: Implemented an advanced search engine using Sphinx to index and search over 15,000 vulnerabilities, enabling fast and accurate searches.",
        "MISP Integration: Successfully integrated with the Malware Information Sharing Platform (MISP), enhancing the cybersecurity infrastructure for efficient sharing and analysis of malware information.",
        "PDF Conversion Module: Implemented a PDF conversion module using the Prawn gem for seamless document generation and manipulation.",
        "Subscription-based API: Created an API to manage user subscriptions, including rate-limiting for stable performance.",
        "Migration to Angular 15: Migrated the project from Angular 5 to Angular 15, improving the user interface and experience.",
        "Dynamic Chart Development: Developed dynamic charts using ng2-charts and apexcharts.js to visually represent data in real-time.",
        "Dynamic Calendar Implementation: Implemented a dynamic calendar allowing users to schedule events and receive notifications, enhancing user engagement.",
        "Vulnerabilities Dashboard: Implemented a responsive Vulnerabilities Dashboard, showcasing attacks' map, last 10 attacks, and attacks categorized by country, type, and source.",
        "Dynamic Threat Map: Developed a dynamic map using Leaflet displaying the threat level for each country, improving the visualization of security data.",
        "Implemented Python Scripts: Developed scripts to collect data from AlienVault, Shodan, and VirusTotal, enhancing cybersecurity data analysis.",
        "Platform Deployment: Deployed and secured access to the 'CERT Axians' platform, focusing on user-friendly and secure front-end features.",
        "Bug Fixing and Troubleshooting: Conducted bug fixing and troubleshooting to ensure the reliability of both back-end and front-end functionalities.",
      ],
      tech: "Angular 5 and 15, Ruby on Rails 5, Ruby, Python(Scripts), redmine3, JWT, JSON, MySQL, Thinking sphinx, Elasticsearch, JavaScript, JQuery, CSS3, HTML5, Bootstrap, GIT",
    },
    {
      company: "6NLG CYBERSECURITY",
      role: "Full Stack Web Developer",
      period: "Oct 2020 – Jun 2021",
      location: "TUNISIA",
      type: "OFFICE",
      description:
        "Development of the 'SECNOLOGY'. The purpose of the application is to coordinate and automate the response to incidents in all fields (finance, security, health, etc.).",
      highlights: [
        "JSON & GCF Configuration Module: Developed a Configuration module utilizing JSON and GCF, providing a modular and configurable approach to application settings.",
        "Automated Log Processing: Enhances data flexibility through customizable log workflows, including compression, decryption, merging, and filtering.",
        "D3.js Statistics Visualization Module: Implemented a Statistics module using D3.js, leveraging dynamic charts and diagrams for in-depth data visualization.",
        "Real-time Notifications: Implemented a module using socket technology for instant incident updates, facilitating prompt user responses.",
        "Python-Selenium Test Automation: Used Python scripts with Selenium for automated testing, ensuring application reliability and quality assurance.",
        "Responsive UI Design and Management: Designed and managed responsive UIs with a focus on cross-browser compatibility and optimal user experience.",
      ],
      tech: "Angular 7, Node.js, D3.js, Python(Scripts), JWT, JSON, Socket io, JavaScript, Express js, CSS3, HTML5, Bootstrap, GIT",
    },
    {
      company: "6NLG CYBERSECURITY",
      role: "Internship",
      period: "Mar 2020 – Sep 2020",
      location: "TUNISIA",
      type: "OFFICE",
      description:
        "Development of a cybersecurity web app 'SECNOLOGY', The application aims at coordinating and automating incident response in all areas.",
      highlights: [
        "Web Modernization: Transformed a C++ desktop application into a responsive web application with Angular and Express.js, enhancing accessibility and platform versatility.",
        "Automated Log Processing: Built the 'Jobs' Module for users to create customizable log processing workflows, freeing analysts and boosting their productivity.",
        "Log toolkit: Compress, decrypt, merge, filter, and more... Handle diverse log formats with ease.",
      ],
      tech: "Angular 7, Node.js, Express js, JWT, JSON, JavaScript, JQuery, CSS3, HTML5, Bootstrap, GIT",
    },
    {
      company: "BIAT Insurance",
      role: "Internship",
      period: "Mar 2018 – Jun 2018",
      location: "TUNISIA",
      type: "OFFICE",
      description:
        "Design and development of an intranet. The application is used to share information and resources within an organization (files, events, articles ...)",
      highlights: [
        "Authentication module: Developed secure authentication using Java Spring Security.",
        "User management module: Utilized Java Spring Security for role management and implemented CRUD operations for user profiles.",
        "Content Management: Created models for events, articles, and files, implementing CRUD operations for each.",
        "Responsive UI Design: Designed responsive user interfaces using html, css, javascript and bootstrap, optimizing for various screen sizes and devices.",
      ],
      tech: "Spring Java, Java Server Pages (JSP), UML, Apache Tomcat, hibernate, OracleDB",
    },
  ],
  fr: [
    {
      company: "AXIANS CYBERSECURITY",
      role: "Développeur Web Full Stack",
      period: "Juin 2021 - Présent",
      location: "TUNISIE",
      type: "À DISTANCE",
      description:
        "Développement de la plateforme 'CERT Axians IT' offrant des services d'alerte, d'information, de supervision et d'analyse pour se protéger contre les attaques informatiques.",
      highlights: [
        "Intégration de l'analyse des malwares: Intégration d'un module d'analyse automatisée des malwares avec Cuckoo Sandbox pour des informations de sécurité améliorées.",
        "Moteur de recherche avec Sphinx: Mise en place d'un moteur de recherche avancé utilisant Sphinx pour indexer et rechercher efficacement plus de 15 000 vulnérabilités.",
        "Intégration MISP: Intégration réussie avec la Plateforme de Partage d'Informations sur les Menaces (MISP), améliorant l'infrastructure de cybersécurité.",
        "Module de conversion PDF: Mise en place d'un module de conversion PDF en utilisant le gem Prawn pour une génération et manipulation de documents sans faille.",
        "API basée sur les abonnements: Création d'une API permettant de gérer les abonnements des utilisateurs, avec limitation de débit pour une performance stable.",
        "Migration vers Angular 15: Migration réussie du projet d'Angular 5 vers Angular 15, améliorant l'interface utilisateur et l'expérience.",
        "Développement des Charts dynamiques: Développement des charts dynamiques en utilisant ng2-charts et apexcharts.js pour représenter visuellement les données en temps réel.",
        "Implémentation d'un calendrier dynamique: Mise en place d'un calendrier dynamique permettant aux utilisateurs de planifier des événements et de recevoir des notifications.",
        "Dashboard des vulnérabilités: Implémentation d'un tableau de bord des vulnérabilités réactif, présentant la carte des attaques et les statistiques.",
        "Carte de menace dynamique: Développement d'une carte dynamique utilisant Leaflet affichant le niveau de menace pour chaque pays.",
        "Implémentation de scripts Python: Développement de scripts pour collecter des données à partir d'AlienVault, Shodan et VirusTotal.",
        "Déploiement de la plateforme: Déploiement et sécurisation de l'accès à la plateforme 'CERT Axians'.",
        "Correction de bugs: Correction de bugs pour garantir la fiabilité des fonctionnalités tant du côté back-end que du côté front-end.",
      ],
      tech: "Angular 5 et 15, Ruby on Rails 5, Ruby, Python(Scripts), redmine3, JWT, JSON, MySQL, Thinking sphinx, Elasticsearch, JavaScript, JQuery, CSS3, HTML5, Bootstrap, GIT",
    },
    {
      company: "6NLG CYBERSECURITY",
      role: "Développeur Web Full Stack",
      period: "Octobre 2020 – Juin 2021",
      location: "TUNISIE",
      type: "SUR SITE",
      description:
        "Développement de 'SECNOLOGY'. Le but de l'application est de coordonner et d'automatiser la réponse aux incidents dans tous les domaines (finance, sécurité, santé, etc).",
      highlights: [
        "Module de configuration JSON & GCF: Développement d'un module de configuration utilisant JSON et GCF, offrant une approche modulaire et configurable.",
        "Traitement automatisé des Log: Améliore la flexibilité des données grâce à des log workflows personnalisables.",
        "Module de visualisation D3.js: Implémentation d'un module de statistiques utilisant D3.js pour une visualisation approfondie des données.",
        "Notifications en temps réel: Mise en place d'un module utilisant la technologie des sockets pour des mises à jour d'incidents instantanées.",
        "Automatisation des tests: Utilisation de scripts Python avec Selenium pour des tests automatisés.",
        "Conception UI responsive: Conception d'interfaces utilisateur réactives avec compatibilité inter-navigateurs.",
      ],
      tech: "Angular 7, Node.js, D3.js, Python(Scripts), JWT, JSON, Socket io, JavaScript, Express js, CSS3, HTML5, Bootstrap, GIT",
    },
    {
      company: "6NLG CYBERSECURITY",
      role: "Stage - Développeur Web Full Stack",
      period: "Mars 2020 – Septembre 2020",
      location: "TUNISIE",
      type: "SUR SITE",
      description:
        "Développement d'une application web de cybersécurité 'SECNOLOGY'. L'application vise à coordonner et automatiser la réponse aux incidents dans tous les domaines.",
      highlights: [
        "Web Modernisation: Transformation d'une application de bureau C++ en une application Web responsive.",
        "Traitement automatisé des Log: Création du module 'Jobs' permettant aux utilisateurs de créer des flux de travail personnalisables.",
        "Boîte à outils de Logs: Compression, déchiffrement, fusion, filtrage, et plus encore...",
      ],
      tech: "Angular 7, Node.js, Express js, JWT, JSON, JavaScript, JQuery, CSS3, HTML5, Bootstrap, GIT",
    },
    {
      company: "BIAT Assurance",
      role: "Stage - Développeur Web",
      period: "Mars 2018 – Juin 2018",
      location: "TUNISIE",
      type: "SUR SITE",
      description:
        "Conception et développement d'un intranet. L'application est utilisée pour partager des informations et des ressources au sein d'une organisation.",
      highlights: [
        "Module d'authentification: Développement d'une authentification sécurisée avec Java Spring Security.",
        "Module de gestion des utilisateurs: Utilisation de Java Spring Security pour la gestion des rôles.",
        "Gestion de contenu: Création de modèles pour les événements, articles et fichiers.",
        "Conception d'UI responsive: Conception d'interfaces utilisateur réactives optimisées pour différents écrans.",
      ],
      tech: "Spring Java, Java Server Pages (JSP), UML, Apache Tomcat, hibernate, OracleDB",
    },
  ],
}
