export const skills = {
  en: {
    languages: [
      "Ruby on Rails",
      "Angular",
      "Node.js",
      "Express.js",
      "TypeScript",
      "React",
      "JavaScript",
      "Ruby",
      "Java",
      "Spring Boot",
      "Python",
      "D3.js",
    ],
    frontEnd: ["HTML5", "CSS3", "Tailwind", "Bootstrap", "jQuery"],
    databases: ["MySQL", "PostgreSQL", "MongoDB", "Elasticsearch", "OracleDB"],
    design: ["Adobe XD", "Figma", "Adobe Photoshop", "Adobe Illustrator"],
    tools: ["VS Code", "Git", "Docker", "Linux", "Windows"],
    other: ["UML", "JWT", "JSON", "Socket.io", "Redmine", "Thinking Sphinx", "Hibernate", "Apache Tomcat"],
  },
  fr: {
    langages: [
      "Ruby on Rails",
      "Angular",
      "Node.js",
      "Express.js",
      "TypeScript",
      "React",
      "JavaScript",
      "Ruby",
      "Java",
      "Spring Boot",
      "Python",
      "D3.js",
    ],
    frontEnd: ["HTML5", "CSS3", "Tailwind", "Bootstrap", "jQuery"],
    "bases de données": ["MySQL", "PostgreSQL", "MongoDB", "Elasticsearch", "OracleDB"],
    design: ["Adobe XD", "Figma", "Adobe Photoshop", "Adobe Illustrator"],
    outils: ["VS Code", "Git", "Docker", "Linux", "Windows"],
    autres: ["UML", "JWT", "JSON", "Socket.io", "Redmine", "Thinking Sphinx", "Hibernate", "Apache Tomcat"],
  },
}

